# Generated by Django 3.1 on 2020-09-11 16:56

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=70, unique=True, verbose_name='email')),
                ('name', models.CharField(default='Anonymous', max_length=50)),
                ('phone', models.CharField(blank=True, max_length=10, null=True)),
                ('session_token', models.CharField(default=0, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='customer', serialize=False, to='custom_user.user')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='delivery_person', serialize=False, to='custom_user.user')),
                ('preferred_location', models.CharField(choices=[('bombay', 'Bombay'), ('ahemdabad', 'Ahemdabad'), ('delhi', 'Delhi'), ('surat', 'Surat'), ('chennai', 'Chennai'), ('banglore', 'Banglore'), ('jaipur', 'Jaipur'), ('pune', 'Pune'), ('hyderabad', 'Hyderabad')], default='ahemdabad', max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('license_plate_no', models.CharField(blank=True, max_length=10, null=True)),
                ('driving_license_number', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HotelAdmin',
            fields=[
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hotel_admin', serialize=False, to='custom_user.user')),
                ('hotel_address', models.CharField(blank=True, max_length=500, null=True)),
                ('hotel_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('hotel_email', models.EmailField(max_length=60, unique=True, verbose_name='Hotel Email')),
                ('hotel_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('fssai_license', models.CharField(blank=True, max_length=14, null=True)),
            ],
        ),
    ]
