# Generated by Django 3.1 on 2020-09-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoteladmin',
            name='hotel_name',
            field=models.CharField(blank=True, default='Random', max_length=100),
        ),
    ]
