# Generated by Django 3.1 on 2020-09-13 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0002_hoteladmin_hotel_name'),
        ('food', '0003_auto_20200912_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='hotel',
            field=models.ForeignKey(default=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='food', to='custom_user.hoteladmin'),
        ),
    ]
